// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xoerpaprfnotscrunzfn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhvZXJwYXByZm5vdHNjcnVuemZuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzA1NzIwODMsImV4cCI6MjA4NjE0ODA4M30.hkSMdyeQ9uetwKjG2lY6VVAlmGfJBoFrETgYiyl5I_c";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});